// _backup/src/app/contact/page.tsx
"use client";

import { MapPin, Phone, Mail, Clock } from "lucide-react";
import { motion } from "framer-motion";

export default function ContactPage() {
  return (
    <div className="pt-24 pb-16 bg-gray-50 min-h-screen">
      <div className="bg-ovkos-black text-white py-24 px-4 relative overflow-hidden">
        {/* Subtle background pattern/image can go here */}
        <div className="absolute inset-0 opacity-10 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-brand-secondary via-ovkos-black to-ovkos-black z-0" />
        
        <motion.div 
          className="relative z-10 max-w-5xl mx-auto text-center"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1 className="text-4xl md:text-6xl font-bold mb-6 tracking-tight text-white">
            Get in Touch
          </h1>
          <p className="text-xl md:text-2xl text-white/80 max-w-2xl mx-auto leading-relaxed font-sans">
            Start securing your future in Uganda today. We are ready to build when you are.
          </p>
        </motion.div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
          
          {/* Contact Information */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <h2 className="text-3xl font-bold text-ovkos-black mb-8">Contact Information</h2>
            <p className="text-gray-600 mb-10 text-lg leading-relaxed font-sans">
              Whether you have a fully formed architectural plan or just a rough idea of what you want to build, our team is ready to consult with you.
            </p>

            <div className="space-y-8 font-sans">
              <div className="flex items-start">
                <div className="w-12 h-12 bg-white shadow-sm border border-gray-100 flex items-center justify-center shrink-0 mr-6">
                  <MapPin className="text-brand-primary" size={24} />
                </div>
                <div>
                  <h4 className="text-lg font-bold text-ovkos-black mb-1">Headquarters</h4>
                  <p className="text-gray-600">Plot 123, Future Avenue<br />Kampala, Uganda</p>
                </div>
              </div>

              <div className="flex items-start">
                <div className="w-12 h-12 bg-white shadow-sm border border-gray-100 flex items-center justify-center shrink-0 mr-6">
                  <Phone className="text-brand-primary" size={24} />
                </div>
                <div>
                  <h4 className="text-lg font-bold text-ovkos-black mb-1">Phone / WhatsApp</h4>
                  <p className="text-gray-600">+256 700 000 000</p>
                  <p className="text-xs text-gray-500 mt-1 uppercase tracking-wider">Available 24/7 for Diaspora</p>
                </div>
              </div>

              <div className="flex items-start">
                <div className="w-12 h-12 bg-white shadow-sm border border-gray-100 flex items-center justify-center shrink-0 mr-6">
                  <Mail className="text-brand-primary" size={24} />
                </div>
                <div>
                  <h4 className="text-lg font-bold text-ovkos-black mb-1">Email</h4>
                  <p className="text-gray-600 mb-1">build@peaceofmind.ug</p>
                  <p className="text-gray-600">invest@tuoconstruction.ug</p>
                </div>
              </div>
              
              <div className="flex items-start">
                <div className="w-12 h-12 bg-white shadow-sm border border-gray-100 flex items-center justify-center shrink-0 mr-6">
                  <Clock className="text-brand-primary" size={24} />
                </div>
                <div>
                  <h4 className="text-lg font-bold text-ovkos-black mb-1">Business Hours</h4>
                  <p className="text-gray-600 text-sm leading-relaxed">
                    Monday - Friday: 8:00 AM - 6:00 PM (EAT)<br />
                    Saturday: By Appointment<br />
                    Sunday: Closed
                  </p>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Contact Form OR Calendly Placeholder */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            <div className="bg-white p-10 shadow-xl border border-gray-100">
              <h2 className="text-2xl font-bold text-ovkos-black mb-6">Send a Message</h2>
              <form className="space-y-6 font-sans">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label htmlFor="firstName" className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">First Name</label>
                    <input 
                      type="text" 
                      id="firstName" 
                      className="w-full px-4 py-3 border border-gray-300 bg-gray-50 focus:bg-white focus:ring-2 focus:ring-brand-primary focus:border-brand-primary transition-colors outline-none"
                      placeholder="John"
                    />
                  </div>
                  <div>
                    <label htmlFor="lastName" className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Last Name</label>
                    <input 
                      type="text" 
                      id="lastName" 
                      className="w-full px-4 py-3 border border-gray-300 bg-gray-50 focus:bg-white focus:ring-2 focus:ring-brand-primary focus:border-brand-primary transition-colors outline-none"
                      placeholder="Doe"
                    />
                  </div>
                </div>

                <div>
                  <label htmlFor="email" className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Email Address</label>
                  <input 
                    type="email" 
                    id="email" 
                    className="w-full px-4 py-3 border border-gray-300 bg-gray-50 focus:bg-white focus:ring-2 focus:ring-brand-primary focus:border-brand-primary transition-colors outline-none"
                    placeholder="john@example.com"
                  />
                </div>

                <div>
                  <label htmlFor="interest" className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Area of Interest</label>
                  <select 
                    id="interest" 
                    className="w-full px-4 py-3 border border-gray-300 bg-gray-50 focus:bg-white focus:ring-2 focus:ring-brand-primary focus:border-brand-primary transition-colors outline-none"
                  >
                    <option>Peace of Mind Package (Residential)</option>
                    <option>Tuo Construction (Commercial/Tourism)</option>
                    <option>General Inquiry</option>
                  </select>
                </div>

                <div>
                  <label htmlFor="message" className="block text-sm font-bold text-gray-700 mb-2 uppercase tracking-wide">Message</label>
                  <textarea 
                    id="message" 
                    rows={5}
                    className="w-full px-4 py-3 border border-gray-300 bg-gray-50 focus:bg-white focus:ring-2 focus:ring-brand-primary focus:border-brand-primary transition-colors outline-none resize-none"
                    placeholder="Tell us about your project..."
                  ></textarea>
                </div>

                <button 
                  type="submit" 
                  className="w-full bg-brand-primary text-white font-bold uppercase tracking-wider py-4 hover:bg-blue-900 transition-colors shadow-md text-sm"
                >
                  Send Inquiry
                </button>
              </form>

              <div className="mt-8 pt-8 border-t border-gray-100 text-center">
                <p className="text-sm text-gray-500 mb-4 font-sans uppercase tracking-widest font-bold">Or schedule a direct call</p>
                {/* Future Calendly Integration Point */}
                <button className="w-full border-2 border-ovkos-black text-ovkos-black font-bold uppercase tracking-wider py-3 hover:bg-ovkos-black hover:text-white transition-colors text-sm font-sans">
                  Book a Consultation
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}

// src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, PhoneCall, Mail, MapPin, Search } from 'lucide-angular';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './contact.component.html',
})
export class ContactComponent {
  readonly PhoneCallIcon = PhoneCall;
  readonly MailIcon = Mail;
  readonly MapPinIcon = MapPin;
  readonly SearchIcon = Search;
}

<div class="flex flex-col min-h-screen">
  <!-- HERO SECTION -->
  <section class="relative pt-32 pb-20 overflow-hidden bg-ovkos-black">
    <div class="absolute inset-0 z-0">
      <div class="absolute inset-0 bg-black/60 z-10"></div>
      <div 
        class="absolute inset-0 z-0 opacity-40 bg-cover bg-center"
        style="background-image: url('https://images.unsplash.com/photo-1516156008625-3a9d6067fc26?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80')"
      ></div>
    </div>
    <div class="relative z-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center pt-10">
      <div class="max-w-3xl mx-auto">
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold text-white tracking-tight mb-6">
          Contact <span class="text-brand-secondary">Us</span>
        </h1>
        <p class="text-lg md:text-xl text-white/80 leading-relaxed max-w-2xl mx-auto">
          We are ready to answer your questions and start building your legacy in Uganda.
        </p>
      </div>
    </div>
  </section>

  <!-- CONTACT INFO & FORM -->
  <section class="py-24 bg-gray-50 flex-grow">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-16">
        
        <!-- Contact Information -->
        <div>
          <h2 class="text-3xl font-bold text-ovkos-black mb-8">Get In Touch</h2>
          <p class="text-gray-600 mb-12 text-lg">
            Whether you're looking to build a residential home or a commercial project, our team is here to guide you through every step of the process.
          </p>

          <div class="space-y-8">
            <div class="flex items-start">
              <div class="bg-brand-secondary/20 p-4 rounded-full mr-6">
                <lucide-icon [img]="MapPinIcon" size="24" class="text-brand-secondary"></lucide-icon>
              </div>
              <div>
                <h4 class="text-lg font-bold text-ovkos-black mb-1">Office Location</h4>
                <p class="text-gray-600">Kampala, Uganda<br/>Serving clients globally</p>
              </div>
            </div>

            <div class="flex items-start">
              <div class="bg-brand-secondary/20 p-4 rounded-full mr-6">
                <lucide-icon [img]="PhoneCallIcon" size="24" class="text-brand-secondary"></lucide-icon>
              </div>
              <div>
                <h4 class="text-lg font-bold text-ovkos-black mb-1">Phone</h4>
                <p class="text-gray-600">+256 788696494</p>
              </div>
            </div>

            <div class="flex items-start">
              <div class="bg-brand-secondary/20 p-4 rounded-full mr-6">
                <lucide-icon [img]="MailIcon" size="24" class="text-brand-secondary"></lucide-icon>
              </div>
              <div>
                <h4 class="text-lg font-bold text-ovkos-black mb-1">Email</h4>
                <p class="text-gray-600">dicapitale&#64;peaceofmindpackage.com<br/>build&#64;peaceofmindpackage.com</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Contact Form -->
        <div class="bg-white p-8 md:p-10 shadow-xl border border-gray-100 mb-8">
          <h3 class="text-2xl font-bold text-ovkos-black mb-6">Send us a Message</h3>
          <form class="space-y-6">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label for="firstName" class="block text-sm font-medium text-gray-700 mb-2">First Name</label>
                <input type="text" id="firstName" name="firstName" class="w-full px-4 py-3 border border-gray-200 focus:outline-none focus:border-brand-primary transition-colors bg-gray-50 focus:bg-white" placeholder="John">
              </div>
              <div>
                <label for="lastName" class="block text-sm font-medium text-gray-700 mb-2">Last Name</label>
                <input type="text" id="lastName" name="lastName" class="w-full px-4 py-3 border border-gray-200 focus:outline-none focus:border-brand-primary transition-colors bg-gray-50 focus:bg-white" placeholder="Doe">
              </div>
            </div>

            <div>
              <label for="email" class="block text-sm font-medium text-gray-700 mb-2">Email Address</label>
              <input type="email" id="email" name="email" class="w-full px-4 py-3 border border-gray-200 focus:outline-none focus:border-brand-primary transition-colors bg-gray-50 focus:bg-white" placeholder="john@example.com">
            </div>

            <div>
              <label for="subject" class="block text-sm font-medium text-gray-700 mb-2">Subject</label>
              <select id="subject" name="subject" class="w-full px-4 py-3 border border-gray-200 focus:outline-none focus:border-brand-primary transition-colors bg-gray-50 focus:bg-white">
                <option value="peace-of-mind">Peace of Mind Package</option>
                <option value="tuo-construction">Tuo Construction</option>
                <option value="other">Other Inquiry</option>
              </select>
            </div>

            <div>
              <label for="message" class="block text-sm font-medium text-gray-700 mb-2">Message</label>
              <textarea id="message" name="message" rows="5" class="w-full px-4 py-3 border border-gray-200 focus:outline-none focus:border-brand-primary transition-colors bg-gray-50 focus:bg-white" placeholder="How can we help you?"></textarea>
            </div>

            <button type="button" class="w-full bg-brand-primary text-white font-bold uppercase tracking-wider py-4 hover:bg-ovkos-black transition-colors flex justify-center items-center gap-2">
              Send Message
            </button>
          </form>
        </div>

      </div>
    </div>
  </section>
</div>
