// src/app/layout/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LucideAngularModule, Facebook, Instagram, Twitter, Linkedin, Mail, Phone, MapPin } from 'lucide-angular';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  templateUrl: './footer.component.html'
})
export class FooterComponent {
  readonly FacebookIcon = Facebook;
  readonly InstagramIcon = Instagram;
  readonly TwitterIcon = Twitter;
  readonly LinkedinIcon = Linkedin;
  readonly MailIcon = Mail;
  readonly PhoneIcon = Phone;
  readonly MapPinIcon = MapPin;
  
  currentYear = new Date().getFullYear();
}

<footer class="bg-brand-primary text-white pt-16 pb-8">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 lg:gap-8">
      <!-- Brand & Hook -->
      <div class="space-y-6">
        <h3 class="text-2xl font-bold tracking-tight text-white uppercase">
          DiCAPITALE
        </h3>
        <p class="text-white/80 text-sm leading-relaxed max-w-xs">
          The ultimate trust-builder for diaspora clients investing in Ugandan properties. We eliminate risk, drama, and distance so you can build generational wealth remotely.
        </p>
        <div class="flex space-x-4">
          <a href="#" class="text-white/70 hover:text-brand-secondary transition-colors">
            <lucide-icon [img]="FacebookIcon" size="20"></lucide-icon>
          </a>
          <a href="https://x.com/Thecapitalevang" target="_blank" rel="noopener noreferrer" class="text-white/70 hover:text-brand-secondary transition-colors">
            <lucide-icon [img]="TwitterIcon" size="20"></lucide-icon>
          </a>
          <a href="#" class="text-white/70 hover:text-brand-secondary transition-colors">
            <lucide-icon [img]="InstagramIcon" size="20"></lucide-icon>
          </a>
          <a href="#" class="text-white/70 hover:text-brand-secondary transition-colors">
            <lucide-icon [img]="LinkedinIcon" size="20"></lucide-icon>
          </a>
        </div>
      </div>

      <!-- Quick Links -->
      <div>
        <h4 class="text-lg font-semibold mb-6 text-brand-secondary uppercase tracking-wider text-sm">Quick Links</h4>
        <ul class="space-y-4">
          <li>
            <a routerLink="/peace-of-mind" class="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
              <span class="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
              Peace of Mind Package
            </a>
          </li>
          <li>
            <a routerLink="/tuo-construction" class="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
              <span class="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
              Tuo Construction
            </a>
          </li>
          <li>
            <a routerLink="/portfolio" class="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
              <span class="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
              Our Portfolio
            </a>
          </li>
          <li>
            <a routerLink="/process" class="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
              <span class="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
              The Process
            </a>
          </li>
          <li>
            <a routerLink="/blog" class="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
              <span class="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
              Diaspora Resources
            </a>
          </li>
        </ul>
      </div>

      <!-- Contact Details -->
      <div>
        <h4 class="text-lg font-semibold mb-6 text-brand-secondary uppercase tracking-wider text-sm">Contact Us</h4>
        <ul class="space-y-4">
          <li class="flex items-start gap-3 text-white/80 text-sm">
            <lucide-icon [img]="MapPinIcon" size="18" class="text-brand-secondary shrink-0 mt-0.5"></lucide-icon>
            <span>Kampala, Uganda<br/>(Serving the Global Diaspora)</span>
          </li>
          <li class="flex items-center gap-3 text-white/80 text-sm">
            <lucide-icon [img]="PhoneIcon" size="18" class="text-brand-secondary shrink-0"></lucide-icon>
            <span>+256 788696494</span>
          </li>
          <li class="flex flex-col gap-1 text-white/80 text-sm">
            <div class="flex items-center gap-3">
              <lucide-icon [img]="MailIcon" size="18" class="text-brand-secondary shrink-0"></lucide-icon>
              <span>dicapitale&#64;peaceofmindpackage.com</span>
            </div>
            <div class="flex items-center gap-3 pl-7">
              <span>build&#64;peaceofmindpackage.com</span>
            </div>
          </li>
        </ul>
      </div>

      <!-- Newsletter -->
      <div>
        <h4 class="text-lg font-semibold mb-6 text-brand-secondary uppercase tracking-wider text-sm">Newsletter</h4>
        <p class="text-white/80 text-sm mb-4">
          Get the latest insights on building in Uganda and avoiding diaspora pitfalls.
        </p>
        <form class="space-y-2">
          <input 
            type="email" 
            placeholder="Your email address" 
            class="w-full bg-white/10 border border-white/20 text-white px-4 py-3 text-sm focus:outline-none focus:border-brand-secondary focus:ring-1 focus:ring-brand-secondary transition-all placeholder:text-white/40"
            required
          />
          <button 
            type="submit" 
            class="w-full bg-brand-secondary text-ovkos-black font-semibold uppercase tracking-wider text-sm px-4 py-3 hover:bg-yellow-400 transition-colors"
          >
            Subscribe
          </button>
        </form>
      </div>
    </div>

    <div class="border-t border-white/10 mt-16 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
      <p class="text-white/60 text-sm">
        © {{ currentYear }} DiCAPITALE Construction. All rights reserved.
      </p>
      <div class="flex space-x-6">
        <a routerLink="/privacy" class="text-white/60 hover:text-white text-sm transition-colors">
          Privacy Policy
        </a>
        <a routerLink="/terms" class="text-white/60 hover:text-white text-sm transition-colors">
          Terms of Service
        </a>
      </div>
    </div>
  </div>
</footer>

// _backup/src/components/layout/Footer.tsx
import Link from "next/link";
import { Facebook, Instagram, Twitter, Linkedin, Mail, Phone, MapPin } from "lucide-react";

export default function Footer() {
  return (
    <footer className="bg-brand-primary text-white pt-16 pb-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 lg:gap-8">
          {/* Brand & Hook */}
          <div className="space-y-6">
            <h3 className="text-2xl font-bold tracking-tight text-white uppercase">
              DiCAPITALE
            </h3>
            <p className="text-white/80 text-sm leading-relaxed max-w-xs">
              The ultimate trust-builder for diaspora clients investing in Ugandan properties. We eliminate risk, drama, and distance so you can build generational wealth remotely.
            </p>
            <div className="flex space-x-4">
              <a href="#" className="text-white/70 hover:text-brand-secondary transition-colors">
                <Facebook size={20} />
              </a>
              <a href="https://x.com/Thecapitalevang" target="_blank" rel="noopener noreferrer" className="text-white/70 hover:text-brand-secondary transition-colors">
                <Twitter size={20} />
              </a>
              <a href="#" className="text-white/70 hover:text-brand-secondary transition-colors">
                <Instagram size={20} />
              </a>
              <a href="#" className="text-white/70 hover:text-brand-secondary transition-colors">
                <Linkedin size={20} />
              </a>
            </div>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="text-lg font-semibold mb-6 text-brand-secondary uppercase tracking-wider text-sm">Quick Links</h4>
            <ul className="space-y-4">
              <li>
                <Link href="/peace-of-mind" className="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
                  Peace of Mind Package
                </Link>
              </li>
              <li>
                <Link href="/tuo-construction" className="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
                  Tuo Construction
                </Link>
              </li>
              <li>
                <Link href="/portfolio" className="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
                  Our Portfolio
                </Link>
              </li>
              <li>
                <Link href="/process" className="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
                  The Process
                </Link>
              </li>
              <li>
                <Link href="/blog" className="text-white/80 hover:text-white transition-colors text-sm flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-brand-secondary rounded-full"></span>
                  Diaspora Resources
                </Link>
              </li>
            </ul>
          </div>

          {/* Contact Details */}
          <div>
            <h4 className="text-lg font-semibold mb-6 text-brand-secondary uppercase tracking-wider text-sm">Contact Us</h4>
            <ul className="space-y-4">
              <li className="flex items-start gap-3 text-white/80 text-sm">
                <MapPin size={18} className="text-brand-secondary shrink-0 mt-0.5" />
                <span>Kampala, Uganda<br/>(Serving the Global Diaspora)</span>
              </li>
              <li className="flex items-center gap-3 text-white/80 text-sm">
                <Phone size={18} className="text-brand-secondary shrink-0" />
                <span>+256 700 000 000</span>
              </li>
              <li className="flex items-center gap-3 text-white/80 text-sm">
                <Mail size={18} className="text-brand-secondary shrink-0" />
                <span>build@peaceofmindpackage.com</span>
              </li>
            </ul>
          </div>

          {/* Newsletter */}
          <div>
            <h4 className="text-lg font-semibold mb-6 text-brand-secondary uppercase tracking-wider text-sm">Newsletter</h4>
            <p className="text-white/80 text-sm mb-4">
              Get the latest insights on building in Uganda and avoiding diaspora pitfalls.
            </p>
            <form className="space-y-2">
              <input 
                type="email" 
                placeholder="Your email address" 
                className="w-full bg-white/10 border border-white/20 text-white px-4 py-3 text-sm focus:outline-none focus:border-brand-secondary focus:ring-1 focus:ring-brand-secondary transition-all placeholder:text-white/40"
                required
              />
              <button 
                type="submit" 
                className="w-full bg-brand-secondary text-ovkos-black font-semibold uppercase tracking-wider text-sm px-4 py-3 hover:bg-yellow-400 transition-colors"
              >
                Subscribe
              </button>
            </form>
          </div>
        </div>

        <div className="border-t border-white/10 mt-16 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-white/60 text-sm">
            © {new Date().getFullYear()} DiCAPITALE Construction. All rights reserved.
          </p>
          <div className="flex space-x-6">
            <Link href="/privacy" className="text-white/60 hover:text-white text-sm transition-colors">
              Privacy Policy
            </Link>
            <Link href="/terms" className="text-white/60 hover:text-white text-sm transition-colors">
              Terms of Service
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}
